/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as InvitationAcceptedRouteImport } from './app/invitation-accepted'
import { Route as DesktopSigninRouteImport } from './app/desktop-signin'
import { Route as AdminRouteImport } from './app/_admin'
import { Route as IndexRouteImport } from './app/index'
import { Route as AdminUsersRouteImport } from './app/_admin/users'
import { Route as AdminSettingsRouteImport } from './app/_admin/settings'
import { Route as AdminDashboardRouteImport } from './app/_admin/dashboard'
import { Route as AdminOrganizationsIndexRouteImport } from './app/_admin/organizations/index'
import { Route as ApiDesktopModelsRouteImport } from './app/api/desktop/models'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as AdminOrganizationsOrganizationIdIndexRouteImport } from './app/_admin/organizations/$organizationId/index'
import { Route as ApiDesktopSigninClaimRouteImport } from './app/api/desktop/signin/claim'
import { Route as AdminOrganizationsOrganizationIdSettingsRouteImport } from './app/_admin/organizations/$organizationId/settings'
import { Route as AdminOrganizationsOrganizationIdModelsRouteImport } from './app/_admin/organizations/$organizationId/models'
import { Route as AdminOrganizationsOrganizationIdMembersRouteImport } from './app/_admin/organizations/$organizationId/members'
import { Route as AdminOrganizationsOrganizationIdApiKeysRouteImport } from './app/_admin/organizations/$organizationId/api-keys'
import { Route as AdminOrganizationsOrganizationIdAccessControlRouteImport } from './app/_admin/organizations/$organizationId/access-control'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAcceptedRoute = InvitationAcceptedRouteImport.update({
  id: '/invitation-accepted',
  path: '/invitation-accepted',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopSigninRoute = DesktopSigninRouteImport.update({
  id: '/desktop-signin',
  path: '/desktop-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiDesktopModelsRoute = ApiDesktopModelsRouteImport.update({
  id: '/api/desktop/models',
  path: '/api/desktop/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsOrganizationIdIndexRoute =
  AdminOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiDesktopSigninClaimRoute = ApiDesktopSigninClaimRouteImport.update({
  id: '/api/desktop/signin/claim',
  path: '/api/desktop/signin/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsOrganizationIdSettingsRoute =
  AdminOrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/organizations/$organizationId/settings',
    path: '/organizations/$organizationId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsOrganizationIdModelsRoute =
  AdminOrganizationsOrganizationIdModelsRouteImport.update({
    id: '/organizations/$organizationId/models',
    path: '/organizations/$organizationId/models',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsOrganizationIdMembersRoute =
  AdminOrganizationsOrganizationIdMembersRouteImport.update({
    id: '/organizations/$organizationId/members',
    path: '/organizations/$organizationId/members',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsOrganizationIdApiKeysRoute =
  AdminOrganizationsOrganizationIdApiKeysRouteImport.update({
    id: '/organizations/$organizationId/api-keys',
    path: '/organizations/$organizationId/api-keys',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsOrganizationIdAccessControlRoute =
  AdminOrganizationsOrganizationIdAccessControlRouteImport.update({
    id: '/organizations/$organizationId/access-control',
    path: '/organizations/$organizationId/access-control',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/dashboard': typeof AdminDashboardRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/organizations/': typeof AdminOrganizationsIndexRoute
  '/organizations/$organizationId/access-control': typeof AdminOrganizationsOrganizationIdAccessControlRoute
  '/organizations/$organizationId/api-keys': typeof AdminOrganizationsOrganizationIdApiKeysRoute
  '/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/models': typeof AdminOrganizationsOrganizationIdModelsRoute
  '/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/dashboard': typeof AdminDashboardRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/organizations': typeof AdminOrganizationsIndexRoute
  '/organizations/$organizationId/access-control': typeof AdminOrganizationsOrganizationIdAccessControlRoute
  '/organizations/$organizationId/api-keys': typeof AdminOrganizationsOrganizationIdApiKeysRoute
  '/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/organizations/$organizationId/models': typeof AdminOrganizationsOrganizationIdModelsRoute
  '/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/_admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/_admin/organizations/$organizationId/access-control': typeof AdminOrganizationsOrganizationIdAccessControlRoute
  '/_admin/organizations/$organizationId/api-keys': typeof AdminOrganizationsOrganizationIdApiKeysRoute
  '/_admin/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/_admin/organizations/$organizationId/models': typeof AdminOrganizationsOrganizationIdModelsRoute
  '/_admin/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/_admin/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/organizations/'
    | '/organizations/$organizationId/access-control'
    | '/organizations/$organizationId/api-keys'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/models'
    | '/organizations/$organizationId/settings'
    | '/api/desktop/signin/claim'
    | '/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/organizations'
    | '/organizations/$organizationId/access-control'
    | '/organizations/$organizationId/api-keys'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/models'
    | '/organizations/$organizationId/settings'
    | '/api/desktop/signin/claim'
    | '/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/_admin/dashboard'
    | '/_admin/settings'
    | '/_admin/users'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/_admin/organizations/'
    | '/_admin/organizations/$organizationId/access-control'
    | '/_admin/organizations/$organizationId/api-keys'
    | '/_admin/organizations/$organizationId/members'
    | '/_admin/organizations/$organizationId/models'
    | '/_admin/organizations/$organizationId/settings'
    | '/api/desktop/signin/claim'
    | '/_admin/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesktopSigninRoute: typeof DesktopSigninRoute
  InvitationAcceptedRoute: typeof InvitationAcceptedRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDesktopModelsRoute: typeof ApiDesktopModelsRoute
  ApiDesktopSigninClaimRoute: typeof ApiDesktopSigninClaimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation-accepted': {
      id: '/invitation-accepted'
      path: '/invitation-accepted'
      fullPath: '/invitation-accepted'
      preLoaderRoute: typeof InvitationAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-signin': {
      id: '/desktop-signin'
      path: '/desktop-signin'
      fullPath: '/desktop-signin'
      preLoaderRoute: typeof DesktopSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations/': {
      id: '/_admin/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/desktop/models': {
      id: '/api/desktop/models'
      path: '/api/desktop/models'
      fullPath: '/api/desktop/models'
      preLoaderRoute: typeof ApiDesktopModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/organizations/$organizationId/': {
      id: '/_admin/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/desktop/signin/claim': {
      id: '/api/desktop/signin/claim'
      path: '/api/desktop/signin/claim'
      fullPath: '/api/desktop/signin/claim'
      preLoaderRoute: typeof ApiDesktopSigninClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/organizations/$organizationId/settings': {
      id: '/_admin/organizations/$organizationId/settings'
      path: '/organizations/$organizationId/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations/$organizationId/models': {
      id: '/_admin/organizations/$organizationId/models'
      path: '/organizations/$organizationId/models'
      fullPath: '/organizations/$organizationId/models'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations/$organizationId/members': {
      id: '/_admin/organizations/$organizationId/members'
      path: '/organizations/$organizationId/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations/$organizationId/api-keys': {
      id: '/_admin/organizations/$organizationId/api-keys'
      path: '/organizations/$organizationId/api-keys'
      fullPath: '/organizations/$organizationId/api-keys'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizations/$organizationId/access-control': {
      id: '/_admin/organizations/$organizationId/access-control'
      path: '/organizations/$organizationId/access-control'
      fullPath: '/organizations/$organizationId/access-control'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdAccessControlRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminOrganizationsOrganizationIdAccessControlRoute: typeof AdminOrganizationsOrganizationIdAccessControlRoute
  AdminOrganizationsOrganizationIdApiKeysRoute: typeof AdminOrganizationsOrganizationIdApiKeysRoute
  AdminOrganizationsOrganizationIdMembersRoute: typeof AdminOrganizationsOrganizationIdMembersRoute
  AdminOrganizationsOrganizationIdModelsRoute: typeof AdminOrganizationsOrganizationIdModelsRoute
  AdminOrganizationsOrganizationIdSettingsRoute: typeof AdminOrganizationsOrganizationIdSettingsRoute
  AdminOrganizationsOrganizationIdIndexRoute: typeof AdminOrganizationsOrganizationIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminOrganizationsOrganizationIdAccessControlRoute:
    AdminOrganizationsOrganizationIdAccessControlRoute,
  AdminOrganizationsOrganizationIdApiKeysRoute:
    AdminOrganizationsOrganizationIdApiKeysRoute,
  AdminOrganizationsOrganizationIdMembersRoute:
    AdminOrganizationsOrganizationIdMembersRoute,
  AdminOrganizationsOrganizationIdModelsRoute:
    AdminOrganizationsOrganizationIdModelsRoute,
  AdminOrganizationsOrganizationIdSettingsRoute:
    AdminOrganizationsOrganizationIdSettingsRoute,
  AdminOrganizationsOrganizationIdIndexRoute:
    AdminOrganizationsOrganizationIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesktopSigninRoute: DesktopSigninRoute,
  InvitationAcceptedRoute: InvitationAcceptedRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDesktopModelsRoute: ApiDesktopModelsRoute,
  ApiDesktopSigninClaimRoute: ApiDesktopSigninClaimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
