import { borderVars, colorVars, spacingVars } from '@astryxdesign/core/theme/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  workbenchTab: {
    display: 'flex',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    padding: 0,
  },
  workspace: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minWidth: 0,
    minHeight: 0,
  },
  pages: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minWidth: 0,
    minHeight: 0,
  },
  panel: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minWidth: 0,
    minHeight: 0,
  },
  hidden: {
    display: 'none',
  },
  strip: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingVars['--spacing-1'],
    flexShrink: 0,
    overflowX: 'auto',
    padding: spacingVars['--spacing-1-5'],
    borderBlockEndWidth: borderVars['--border-width'],
    borderBlockEndStyle: 'solid',
    borderBlockEndColor: colorVars['--color-border'],
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingVars['--spacing-1'],
    flexShrink: 0,
    padding: spacingVars['--spacing-1-5'],
    borderBlockEndWidth: borderVars['--border-width'],
    borderBlockEndStyle: 'solid',
    borderBlockEndColor: colorVars['--color-border'],
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    maxWidth: '12rem',
    borderWidth: borderVars['--border-width'],
    borderStyle: 'solid',
    borderColor: colorVars['--color-border'],
  },
  tabSelect: {
    overflow: 'hidden',
    paddingBlock: spacingVars['--spacing-1'],
    paddingInline: spacingVars['--spacing-2'],
    border: 0,
    backgroundColor: 'transparent',
    color: colorVars['--color-text-primary'],
    cursor: 'pointer',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  selectedTab: {
    backgroundColor: colorVars['--color-background-muted'],
  },
  addressForm: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
  },
  address: {
    width: '100%',
    minWidth: 0,
    paddingBlock: spacingVars['--spacing-1-5'],
    paddingInline: spacingVars['--spacing-2'],
    borderWidth: borderVars['--border-width'],
    borderStyle: 'solid',
    borderColor: colorVars['--color-border'],
    backgroundColor: colorVars['--color-background-surface'],
    color: colorVars['--color-text-primary'],
    fontFamily: 'inherit',
    fontSize: 'inherit',
  },
  status: {
    minWidth: '3rem',
    color: colorVars['--color-text-secondary'],
    fontSize: '0.75rem',
  },
  viewport: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  error: {
    paddingBlock: spacingVars['--spacing-2'],
    paddingInline: spacingVars['--spacing-3'],
    color: colorVars['--color-error'],
  },
  empty: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingVars['--spacing-2'],
    color: colorVars['--color-text-secondary'],
  },
});
