/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as InvitationAcceptedRouteImport } from './app/invitation-accepted'
import { Route as DesktopSigninRouteImport } from './app/desktop-signin'
import { Route as AccessRouteImport } from './app/access'
import { Route as ConsoleRouteImport } from './app/_console'
import { Route as IndexRouteImport } from './app/index'
import { Route as OrgIndexRouteImport } from './app/org/index'
import { Route as ApiHealthRouteImport } from './app/api/health'
import { Route as ConsoleUsersRouteImport } from './app/_console/users'
import { Route as ConsoleSettingsRouteImport } from './app/_console/settings'
import { Route as ConsoleDashboardRouteImport } from './app/_console/dashboard'
import { Route as OrgOrganizationIdRouteRouteImport } from './app/org/$organizationId/route'
import { Route as OrgOrganizationIdIndexRouteImport } from './app/org/$organizationId/index'
import { Route as ConsoleOrganizationsIndexRouteImport } from './app/_console/organizations/index'
import { Route as OrgOrganizationIdSettingsRouteImport } from './app/org/$organizationId/settings'
import { Route as OrgOrganizationIdModelsRouteImport } from './app/org/$organizationId/models'
import { Route as OrgOrganizationIdMembersRouteImport } from './app/org/$organizationId/members'
import { Route as OrgOrganizationIdApiKeysRouteImport } from './app/org/$organizationId/api-keys'
import { Route as OrgOrganizationIdAccessControlRouteImport } from './app/org/$organizationId/access-control'
import { Route as ApiDesktopModelsRouteImport } from './app/api/desktop/models'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as ConsoleOrganizationsOrganizationIdIndexRouteImport } from './app/_console/organizations/$organizationId/index'
import { Route as ApiDesktopSigninClaimRouteImport } from './app/api/desktop/signin/claim'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAcceptedRoute = InvitationAcceptedRouteImport.update({
  id: '/invitation-accepted',
  path: '/invitation-accepted',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopSigninRoute = DesktopSigninRouteImport.update({
  id: '/desktop-signin',
  path: '/desktop-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleUsersRoute = ConsoleUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const OrgOrganizationIdRouteRoute = OrgOrganizationIdRouteRouteImport.update({
  id: '/org/$organizationId',
  path: '/org/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrganizationIdIndexRoute = OrgOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrganizationIdRouteRoute,
} as any)
const ConsoleOrganizationsIndexRoute =
  ConsoleOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const OrgOrganizationIdSettingsRoute =
  OrgOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgOrganizationIdRouteRoute,
  } as any)
const OrgOrganizationIdModelsRoute = OrgOrganizationIdModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => OrgOrganizationIdRouteRoute,
} as any)
const OrgOrganizationIdMembersRoute =
  OrgOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrgOrganizationIdRouteRoute,
  } as any)
const OrgOrganizationIdApiKeysRoute =
  OrgOrganizationIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => OrgOrganizationIdRouteRoute,
  } as any)
const OrgOrganizationIdAccessControlRoute =
  OrgOrganizationIdAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => OrgOrganizationIdRouteRoute,
  } as any)
const ApiDesktopModelsRoute = ApiDesktopModelsRouteImport.update({
  id: '/api/desktop/models',
  path: '/api/desktop/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleOrganizationsOrganizationIdIndexRoute =
  ConsoleOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ApiDesktopSigninClaimRoute = ApiDesktopSigninClaimRouteImport.update({
  id: '/api/desktop/signin/claim',
  path: '/api/desktop/signin/claim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/org/$organizationId': typeof OrgOrganizationIdRouteRouteWithChildren
  '/dashboard': typeof ConsoleDashboardRoute
  '/settings': typeof ConsoleSettingsRoute
  '/users': typeof ConsoleUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/org/': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/org/$organizationId/access-control': typeof OrgOrganizationIdAccessControlRoute
  '/org/$organizationId/api-keys': typeof OrgOrganizationIdApiKeysRoute
  '/org/$organizationId/members': typeof OrgOrganizationIdMembersRoute
  '/org/$organizationId/models': typeof OrgOrganizationIdModelsRoute
  '/org/$organizationId/settings': typeof OrgOrganizationIdSettingsRoute
  '/organizations/': typeof ConsoleOrganizationsIndexRoute
  '/org/$organizationId/': typeof OrgOrganizationIdIndexRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/organizations/$organizationId/': typeof ConsoleOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/settings': typeof ConsoleSettingsRoute
  '/users': typeof ConsoleUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/org': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/org/$organizationId/access-control': typeof OrgOrganizationIdAccessControlRoute
  '/org/$organizationId/api-keys': typeof OrgOrganizationIdApiKeysRoute
  '/org/$organizationId/members': typeof OrgOrganizationIdMembersRoute
  '/org/$organizationId/models': typeof OrgOrganizationIdModelsRoute
  '/org/$organizationId/settings': typeof OrgOrganizationIdSettingsRoute
  '/organizations': typeof ConsoleOrganizationsIndexRoute
  '/org/$organizationId': typeof OrgOrganizationIdIndexRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/organizations/$organizationId': typeof ConsoleOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/access': typeof AccessRoute
  '/desktop-signin': typeof DesktopSigninRoute
  '/invitation-accepted': typeof InvitationAcceptedRoute
  '/sign-in': typeof SignInRoute
  '/org/$organizationId': typeof OrgOrganizationIdRouteRouteWithChildren
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/users': typeof ConsoleUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/org/': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/models': typeof ApiDesktopModelsRoute
  '/org/$organizationId/access-control': typeof OrgOrganizationIdAccessControlRoute
  '/org/$organizationId/api-keys': typeof OrgOrganizationIdApiKeysRoute
  '/org/$organizationId/members': typeof OrgOrganizationIdMembersRoute
  '/org/$organizationId/models': typeof OrgOrganizationIdModelsRoute
  '/org/$organizationId/settings': typeof OrgOrganizationIdSettingsRoute
  '/_console/organizations/': typeof ConsoleOrganizationsIndexRoute
  '/org/$organizationId/': typeof OrgOrganizationIdIndexRoute
  '/api/desktop/signin/claim': typeof ApiDesktopSigninClaimRoute
  '/_console/organizations/$organizationId/': typeof ConsoleOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/org/$organizationId'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/org/'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/org/$organizationId/access-control'
    | '/org/$organizationId/api-keys'
    | '/org/$organizationId/members'
    | '/org/$organizationId/models'
    | '/org/$organizationId/settings'
    | '/organizations/'
    | '/org/$organizationId/'
    | '/api/desktop/signin/claim'
    | '/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/org'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/org/$organizationId/access-control'
    | '/org/$organizationId/api-keys'
    | '/org/$organizationId/members'
    | '/org/$organizationId/models'
    | '/org/$organizationId/settings'
    | '/organizations'
    | '/org/$organizationId'
    | '/api/desktop/signin/claim'
    | '/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/access'
    | '/desktop-signin'
    | '/invitation-accepted'
    | '/sign-in'
    | '/org/$organizationId'
    | '/_console/dashboard'
    | '/_console/settings'
    | '/_console/users'
    | '/api/health'
    | '/org/'
    | '/api/auth/$'
    | '/api/desktop/models'
    | '/org/$organizationId/access-control'
    | '/org/$organizationId/api-keys'
    | '/org/$organizationId/members'
    | '/org/$organizationId/models'
    | '/org/$organizationId/settings'
    | '/_console/organizations/'
    | '/org/$organizationId/'
    | '/api/desktop/signin/claim'
    | '/_console/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  AccessRoute: typeof AccessRoute
  DesktopSigninRoute: typeof DesktopSigninRoute
  InvitationAcceptedRoute: typeof InvitationAcceptedRoute
  SignInRoute: typeof SignInRoute
  OrgOrganizationIdRouteRoute: typeof OrgOrganizationIdRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  OrgIndexRoute: typeof OrgIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDesktopModelsRoute: typeof ApiDesktopModelsRoute
  ApiDesktopSigninClaimRoute: typeof ApiDesktopSigninClaimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation-accepted': {
      id: '/invitation-accepted'
      path: '/invitation-accepted'
      fullPath: '/invitation-accepted'
      preLoaderRoute: typeof InvitationAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-signin': {
      id: '/desktop-signin'
      path: '/desktop-signin'
      fullPath: '/desktop-signin'
      preLoaderRoute: typeof DesktopSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/users': {
      id: '/_console/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ConsoleUsersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/org/$organizationId': {
      id: '/org/$organizationId'
      path: '/org/$organizationId'
      fullPath: '/org/$organizationId'
      preLoaderRoute: typeof OrgOrganizationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$organizationId/': {
      id: '/org/$organizationId/'
      path: '/'
      fullPath: '/org/$organizationId/'
      preLoaderRoute: typeof OrgOrganizationIdIndexRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/_console/organizations/': {
      id: '/_console/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ConsoleOrganizationsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/org/$organizationId/settings': {
      id: '/org/$organizationId/settings'
      path: '/settings'
      fullPath: '/org/$organizationId/settings'
      preLoaderRoute: typeof OrgOrganizationIdSettingsRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/org/$organizationId/models': {
      id: '/org/$organizationId/models'
      path: '/models'
      fullPath: '/org/$organizationId/models'
      preLoaderRoute: typeof OrgOrganizationIdModelsRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/org/$organizationId/members': {
      id: '/org/$organizationId/members'
      path: '/members'
      fullPath: '/org/$organizationId/members'
      preLoaderRoute: typeof OrgOrganizationIdMembersRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/org/$organizationId/api-keys': {
      id: '/org/$organizationId/api-keys'
      path: '/api-keys'
      fullPath: '/org/$organizationId/api-keys'
      preLoaderRoute: typeof OrgOrganizationIdApiKeysRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/org/$organizationId/access-control': {
      id: '/org/$organizationId/access-control'
      path: '/access-control'
      fullPath: '/org/$organizationId/access-control'
      preLoaderRoute: typeof OrgOrganizationIdAccessControlRouteImport
      parentRoute: typeof OrgOrganizationIdRouteRoute
    }
    '/api/desktop/models': {
      id: '/api/desktop/models'
      path: '/api/desktop/models'
      fullPath: '/api/desktop/models'
      preLoaderRoute: typeof ApiDesktopModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/organizations/$organizationId/': {
      id: '/_console/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof ConsoleOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/api/desktop/signin/claim': {
      id: '/api/desktop/signin/claim'
      path: '/api/desktop/signin/claim'
      fullPath: '/api/desktop/signin/claim'
      preLoaderRoute: typeof ApiDesktopSigninClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleUsersRoute: typeof ConsoleUsersRoute
  ConsoleOrganizationsIndexRoute: typeof ConsoleOrganizationsIndexRoute
  ConsoleOrganizationsOrganizationIdIndexRoute: typeof ConsoleOrganizationsOrganizationIdIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleUsersRoute: ConsoleUsersRoute,
  ConsoleOrganizationsIndexRoute: ConsoleOrganizationsIndexRoute,
  ConsoleOrganizationsOrganizationIdIndexRoute:
    ConsoleOrganizationsOrganizationIdIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface OrgOrganizationIdRouteRouteChildren {
  OrgOrganizationIdAccessControlRoute: typeof OrgOrganizationIdAccessControlRoute
  OrgOrganizationIdApiKeysRoute: typeof OrgOrganizationIdApiKeysRoute
  OrgOrganizationIdMembersRoute: typeof OrgOrganizationIdMembersRoute
  OrgOrganizationIdModelsRoute: typeof OrgOrganizationIdModelsRoute
  OrgOrganizationIdSettingsRoute: typeof OrgOrganizationIdSettingsRoute
  OrgOrganizationIdIndexRoute: typeof OrgOrganizationIdIndexRoute
}

const OrgOrganizationIdRouteRouteChildren: OrgOrganizationIdRouteRouteChildren =
  {
    OrgOrganizationIdAccessControlRoute: OrgOrganizationIdAccessControlRoute,
    OrgOrganizationIdApiKeysRoute: OrgOrganizationIdApiKeysRoute,
    OrgOrganizationIdMembersRoute: OrgOrganizationIdMembersRoute,
    OrgOrganizationIdModelsRoute: OrgOrganizationIdModelsRoute,
    OrgOrganizationIdSettingsRoute: OrgOrganizationIdSettingsRoute,
    OrgOrganizationIdIndexRoute: OrgOrganizationIdIndexRoute,
  }

const OrgOrganizationIdRouteRouteWithChildren =
  OrgOrganizationIdRouteRoute._addFileChildren(
    OrgOrganizationIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  AccessRoute: AccessRoute,
  DesktopSigninRoute: DesktopSigninRoute,
  InvitationAcceptedRoute: InvitationAcceptedRoute,
  SignInRoute: SignInRoute,
  OrgOrganizationIdRouteRoute: OrgOrganizationIdRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  OrgIndexRoute: OrgIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDesktopModelsRoute: ApiDesktopModelsRoute,
  ApiDesktopSigninClaimRoute: ApiDesktopSigninClaimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
