/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/foundryTheme.ts
 * Command: astryx theme build src/foundryTheme.ts --out src/built/foundry.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./foundry.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const foundryTheme: DefinedTheme;
