/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/kiraTheme.ts
 * Command: astryx theme build src/kiraTheme.ts --out src/built/kira.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./kira.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const kiraTheme: DefinedTheme;
